# Generated by Django 3.2.5 on 2021-07-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('home_team', models.CharField(max_length=100)),
                ('home_score', models.IntegerField()),
                ('away_team', models.CharField(max_length=100)),
                ('away_score', models.IntegerField()),
            ],
        ),
    ]
