# Generated by Django 3.2.5 on 2021-08-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_report',
            field=models.TextField(default='No report available. Our journalist was on holiday.', max_length=2000),
        ),
    ]
